# Generated by Django 5.2.1 on 2025-05-15 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='slug',
        ),
    ]
